### ISSUE TITLE
lcdCharDef not working

### ISSUE THREAD

**Issue by ghost** [WiringPi/WiringPi-Python#13]
The c-version of this command needs an "unsigned char [8]" type to work.
When i try to define a new char like this in python using this library:
newChar = [
    0b11111,
    0b10001,
    0b10001,
    0b10101,
    0b11111,
    0b10001,
    0b10001,
    0b11111
]

and pass it to wiringpi2:
wiringpi2.lcdCharDef (lcdHandle, 2, newChar)

i get the following error in command line:
TypeError: in method 'lcdCharDef', argument 3 of type 'unsigned char [8]'

Maybe i am wrong (i just play around with python since a few days), but i can't find any way to get this working.

Additional it seem that this function is missing complete in the GPIO class code part of wiringpi2.py.

**Comment by Gadgetoid** [comment]
I've now added what I believe to be a fix for this. See https://github.com/WiringPi/WiringPi-Python/issues/20 for details.

I can't *test* it right now, however, because I don't have an LCD to hand.
