### ISSUE TITLE
SPI parameter list API

### ISSUE THREAD

**Issue by MaxBaex** [WiringPi/WiringPi-Python#3]
The function wiringPiSPIDataRW is returning a -1. I 
I could not find a API documentation, so I assume I do not pass the right parameter. 
What does the function expect? 
first parameter channel = 0
second parameter list with numbers in the range 0 ... 255 ? 
no third parameter?

Thanks 
Cheers
Max

**Comment by ihcfan** [comment]
I know this is old...but in case someone else stumbles upon it...
Under python...wiringPiSPIDataRW expects two parameters, the channel and a string of bytes.  Typically the bytes are constructed from a byte array str(bytearray([x,y,z]))
