### ISSUE TITLE
Multiple README files

### ISSUE THREAD

**Issue by lurch** [WiringPi/WiringPi-Python#30]
This project currently has a `README`, a `README.md` **and** a `README.rst` !
It would be nice if the unused files could be deleted so that we know which is the *real* README ;-)

P.S. Nice to see some action in this repo again :+1:

**Comment by Gadgetoid** [comment]
It's been far too long. I've made a right royal mess of things! Found a bit of time to try and get everything back on the rails.

Fixed: https://github.com/WiringPi/WiringPi-Python/commit/a012c7151b8dd33ae1e96acd9b5ced364d89ccca

**Comment by lurch** [comment]
Great :-)
