### ISSUE TITLE
Missing cd in README.md

### ISSUE THREAD

**Issue by csatt** [WiringPi/WiringPi-Python#36]
The instructions in the README have the following:

Build WiringPi
  cd WiringPi
  sudo ./build 
Generate Bindings
  swig2.0 -python wiringpi.i or swig3.0 -thread -python wiringpi.i

There should be a "cd .." before the swig command.

**Comment by koppi** [comment]
The README.md states:

```bash
sudo ./build
```
but what actually works is:
```bash
sudo ./build.sh
```

**Comment by liffiton** [comment]
[Cleaning up old issues.]
The earlier commit fixed this, and build.sh is now unneeded/gone as well.
