### ISSUE TITLE
Functions with pointers as parameters

### ISSUE THREAD

**Issue by Jorawar-Singh** [WiringPi/WiringPi-Python#52]
Some functions like:
lcd128x64getScreenSize and lcd128x64orientCoordinates
demand an 'int *' type input.

Python doesn't use pointers. 
How does one then use these functions?

`in method 'lcd128x64getScreenSize', argument 1 of type 'int *'`

**Comment by Gadgetoid** [comment]
I believe this requires a `typemap` in SWIG in order to set up a C translation function that takes a standard Python object, converts it to an `int *` pointer and then cleans up after itself. It should be possible.
