### ISSUE TITLE
Python package does not contain what is claims.

### ISSUE THREAD

**Issue by frosch01** [WiringPi/WiringPi-Python#54]
Hi,

I just decided to switch in my project using wiringpi from Python. I installed the package using pip/pip3 on Raspbian on a PI ZeroW and ran into the problems described in #49 and #47. I am able to run the native wiringpi gpio tool doing exactly the things I want to do with Python. So I checked versions and found the Python package to be at the same version as Debian package I received from apt.    

So I checked what is contained in the Python package and finally found that the version shipped in the tar.gz is _NOT_ 4.22.0 by comparing the sources. 

Perhaps the git submodule update was missing as the package archive was build. Is the archive the package was build from available on some branch? I was not able to find a branch where the version 4.22.0 is provided beside the one from this PR: https://github.com/WiringPi/WiringPi-Python/pull/51 

I downloaded the package now from neuralpi:master and can confirm that this one runs without the described issues.

**Comment by Gadgetoid** [comment]
I have now merged PR #51 and release a new package to PIP with a minor version bump to: `2.44.1`

I must clearly have, as you suggest, failed to update the submodule. D'oh.
