### ISSUE TITLE
Using the SPI and I2C Functions

### ISSUE THREAD

**Issue by sierraritter** [WiringPi/WiringPi-Python#67]
I see that the software for SPI is easy to use if you're just using chip select 0 and 1, CS0 and CS1. I understand how that works, but I want 5 devices on SPI. So I'm using GPIO on the Pi for the chip selects. Is this possible to edit the function SPIchannel = 1 to set SPIchannel to a GPIO pin directly?

Same with two devices on I2C as opposed to a single device.

**Comment by liffiton** [comment]
This library is just exposing the wiringpi API in Python, not adding to or making any changes to it.  I don't believe it or the underlying kernel functionality allows for using arbitrary GPIO pins as SPI chip enables.  You could write your own function that wraps the existing SPI function(s), setting your GPIO pins as desired before and/or after each call.

I2C is an addressable interface, so you can attach multiple devices to the one bus, and the wiringpi API supports that.

**Comment by sierraritter** [comment]
@liffiton Thank you for your feedback, especially at such a quick response! Do you have any advice for writing my own functions to do that?

**Comment by liffiton** [comment]
You're welcome!

It depends on your specific needs and setup, but it might work something like this

``` python
select_pins = [10, 11, 12, 13, 14]  # GPIO pin numbers for your chip selects

def mySPI(which_GPIO, buffer):
    # set selected GPIO high, all others low
    for pin in select_pins:
        wiringpi.digitalWrite(pin, 1 if pin == which_GPIO else 0)

    # perform RW operation
    wiringpi.wiringPiSPIDataRW(0, buffer)   # the CE0 pin will be toggled, so it should not be connected to anything

    # set all select pins low
    for pin in select_pins:
        wiringpi.digitalWrite(pin, 0)
```

I haven't used SPI myself, so I could well have something wrong there.  I'm not familiar with exactly how SPI uses the chip enable pins, so this might not work at all.  That's the general idea I'd pursue, though.

**Comment by sierraritter** [comment]
This direction is incredibly helpful. I'll post if I make any progress. Thank you very, very much!
